import { useGetPost } from "@/apis";
import { PostCard } from "@/containers";
import { useLayout } from "@/hooks";
import Head from "next/head";
import { useRouter } from "next/router";

const PostPage = () => {
  const { Layout } = useLayout();

  const router = useRouter();
  const { data: post } = useGetPost(
    router.query?.id ? +router.query.id : undefined
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PostCard post={post} />
      </Layout>
    </>
  );
};

export default PostPage;
