import { useGetPosts } from "@/apis";
import Layout from "@/components/Layout";
import PageOptions from "@/components/PageOptions";
import ViewOptions from "@/components/ViewOptions";
import PostsTable from "@/containers/posts/PostsTable";
import { Flex } from "@chakra-ui/react";
import Head from "next/head";

const PostsAllPage = () => {
  const { data } = useGetPosts();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Flex direction={"column"} gap={4}>
          <Flex justifyContent={"space-between"}>
            <Flex gap={4}>
              <ViewOptions />
              <PageOptions />
            </Flex>
          </Flex>
          <PostsTable posts={data ?? []} />
        </Flex>
      </Layout>
    </>
  );
};

export default PostsAllPage;
