import Layout from "@/components/Layout";
import PageOptions from "@/components/PageOptions";
import ViewOptions from "@/components/ViewOptions";
import PostsByCursor from "@/containers/posts/PostsByCursor";
import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";

const PostsCursorPage = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Flex direction={"column"} gap={4}>
          <Flex justifyContent={"space-between"}>
            <Flex gap={4}>
              <ViewOptions />
              <PageOptions />
            </Flex>
          </Flex>
          <PostsByCursor observe={router.query?.type === "observer"} />
        </Flex>
      </Layout>
    </>
  );
};

export default PostsCursorPage;
