import { PostCreateForm } from "@/containers";
import { useLayout } from "@/hooks";
import Head from "next/head";

const WritePostPage = () => {
  const { Layout } = useLayout();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PostCreateForm />
      </Layout>
    </>
  );
};

export default WritePostPage;
