import { ResponsiveLayout } from "@/components";
import { PostCreateForm } from "@/containers";
import Head from "next/head";

const WritePostPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveLayout>
        <PostCreateForm />
      </ResponsiveLayout>
    </>
  );
};

export default WritePostPage;
