import { Button, Center, Flex, Heading, Text } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";

const NotFoundPage = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center
        flexDirection={"column"}
        w={"100vw"}
        h={"100vh"}
        gap={"8"}
        pb={"20"}
      >
        <Flex direction={"column"} gap={"2"} align={"center"}>
          <Heading>404</Heading>
          <Text fontSize={"lg"}>This page could not be found.</Text>
        </Flex>
        <Button onClick={router.back}>Go back</Button>
      </Center>
    </>
  );
};

export default NotFoundPage;
