import Layout from "@/components/Layout";
import { Button, Flex } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Flex gap={4}>
          <Button onClick={() => router.push({ pathname: "/users" })}>
            Users
          </Button>
          <Button onClick={() => router.push({ pathname: "/posts" })}>
            Posts
          </Button>
        </Flex>
      </Layout>
    </>
  );
}
