import Layout from "@/components/Layout";
import PageOptions from "@/components/PageOptions";
import ViewOptions from "@/components/ViewOptions";
import { ViewOptionQueries } from "@/constants";
import PostsAll from "@/containers/posts/PostsAll";
import PostsByCursor from "@/containers/posts/PostsByCursor";
import PostsByOffset from "@/containers/posts/PostsByOffset";
import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";

const PostsAllPage = () => {
  const router = useRouter();
  const viewOption = router.query?.view as ViewOptionQueries;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Flex direction={"column"} gap={4}>
          <Flex justifyContent={"space-between"}>
            <Flex gap={4}>
              <ViewOptions />
              {viewOption !== ViewOptionQueries.All && <PageOptions />}
            </Flex>
          </Flex>
          {viewOption === ViewOptionQueries.All && <PostsAll />}
          {viewOption === ViewOptionQueries.Offset && <PostsByOffset />}
          {(viewOption === ViewOptionQueries.CursorButton ||
            viewOption === ViewOptionQueries.CursorObserver) && (
            <PostsByCursor
              observe={viewOption === ViewOptionQueries.CursorObserver}
            />
          )}
        </Flex>
      </Layout>
    </>
  );
};

export default PostsAllPage;
