import { useGetUser } from "@/apis";
import { ResponsiveLayout } from "@/components";
import { UserCard } from "@/containers";
import { QueryParser } from "@/utils";
import Head from "next/head";
import { useRouter } from "next/router";

const UserPage = () => {
  const router = useRouter();
  const { data: user } = useGetUser(QueryParser.toNumber(router.query.id));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveLayout>
        <UserCard data={user} />
      </ResponsiveLayout>
    </>
  );
};

export default UserPage;
