import { useGetUsers } from "@/apis";
import Layout from "@/components/Layout";
import CreateUserModal from "@/containers/users/CreateUserModal";
import UsersTab from "@/containers/users/UsersTab";
import UsersTable from "@/containers/users/UsersTable";
import UsersUtils from "@/containers/users/UsersUtils";
import { Divider, Flex, useDisclosure } from "@chakra-ui/react";
import Head from "next/head";

const UsersAllPage = () => {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const { data } = useGetUsers();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <CreateUserModal isOpen={isOpen} onClose={onClose} />
        <Flex direction={"column"} gap={4}>
          <UsersUtils onCreateUser={onOpen} />
          <Divider />
          <UsersTab />
          <UsersTable users={data ?? []} />
        </Flex>
      </Layout>
    </>
  );
};

export default UsersAllPage;
