import { useGetUsers } from "@/apis";
import Layout from "@/components/Layout";
import PageOptions from "@/components/PageOptions";
import ViewOptions from "@/components/ViewOptions";
import UserCreateModal from "@/containers/users/UserCreateModal";
import UsersTable from "@/containers/users/UsersTable";
import UsersUtils from "@/containers/users/UsersUtils";
import { Flex, useDisclosure } from "@chakra-ui/react";
import Head from "next/head";

const UsersAllPage = () => {
  const { isOpen, onOpen, onClose } = useDisclosure();

  const { data } = useGetUsers();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <UserCreateModal isOpen={isOpen} onClose={onClose} />
        <Flex direction={"column"} gap={4}>
          <Flex justifyContent={"space-between"}>
            <UsersUtils onCreateUser={onOpen} />
            <Flex gap={4}>
              <ViewOptions />
              <PageOptions />
            </Flex>
          </Flex>
          <UsersTable users={data ?? []} />
        </Flex>
      </Layout>
    </>
  );
};

export default UsersAllPage;
