import Layout from "@/components/Layout";
import UserCreateModal from "@/containers/users/UserCreateModal";
import UsersByCursor from "@/containers/users/UsersByCursor";
import UsersTab from "@/containers/users/UsersTab";
import UsersUtils from "@/containers/users/UsersUtils";
import { Divider, Flex, useDisclosure } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";

const UsersCursorPage = () => {
  const router = useRouter();
  const { isOpen, onOpen, onClose } = useDisclosure();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <UserCreateModal isOpen={isOpen} onClose={onClose} />
        <Flex direction={"column"} gap={4}>
          <UsersUtils onCreateUser={onOpen} />
          <Divider />
          <UsersTab />
          <UsersByCursor observe={router.query?.type === "observer"} />
        </Flex>
      </Layout>
    </>
  );
};

export default UsersCursorPage;
