import { useCreateTestUsers } from "@/apis";
import Layout from "@/components/Layout";
import UserForm from "@/containers/users/UserForm";
import UsersAll from "@/containers/users/UsersAll";
import UserList from "@/containers/users/UsersByCursor";
import UsersByOffset from "@/containers/users/UsersByOffset";
import {
  Button,
  Divider,
  Flex,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
} from "@chakra-ui/react";
import Head from "next/head";

const tabs = ["Users", "Users Offset", "Users Cursor"];
const count = 50;

const Users = () => {
  const { mutate: createTestUsers, isLoading } = useCreateTestUsers(count);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Flex direction={"column"} gap={4}>
          <Button onClick={() => createTestUsers({})} isDisabled={isLoading}>
            {`Create ${count} Users`}
          </Button>
          <UserForm />
          <Divider />
          <Tabs variant="enclosed">
            <TabList>
              {tabs.map((tab) => (
                <Tab key={tab}>{tab}</Tab>
              ))}
            </TabList>
            <TabPanels>
              <TabPanel>
                <UsersAll />
              </TabPanel>
              <TabPanel>
                <UsersByOffset />
              </TabPanel>
              <TabPanel>
                <UserList />
              </TabPanel>
            </TabPanels>
          </Tabs>
        </Flex>
      </Layout>
    </>
  );
};

export default Users;
