import Layout from "@/components/Layout";
import PageOptions from "@/components/PageOptions";
import ViewOptions from "@/components/ViewOptions";
import { ViewOptionQueries } from "@/constants";
import UserCreateModal from "@/containers/users/UserCreateModal";
import UsersAll from "@/containers/users/UsersAll";
import UsersByCursor from "@/containers/users/UsersByCursor";
import UsersByOffset from "@/containers/users/UsersByOffset";
import UsersUtils from "@/containers/users/UsersUtils";
import { Flex, useDisclosure } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";

const UsersPage = () => {
  const { isOpen, onOpen, onClose } = useDisclosure();

  const router = useRouter();
  const viewOption = router.query?.view as ViewOptionQueries;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <UserCreateModal isOpen={isOpen} onClose={onClose} />
        <Flex direction={"column"} gap={4}>
          <Flex justifyContent={"space-between"}>
            <UsersUtils onCreateUser={onOpen} />
            <Flex gap={4}>
              <ViewOptions />
              {viewOption !== ViewOptionQueries.All && <PageOptions />}
            </Flex>
          </Flex>
          {viewOption === ViewOptionQueries.All && <UsersAll />}
          {viewOption === ViewOptionQueries.Offset && <UsersByOffset />}
          {(viewOption === ViewOptionQueries.CursorButton ||
            viewOption === ViewOptionQueries.CursorObserver) && (
            <UsersByCursor
              observe={viewOption === ViewOptionQueries.CursorObserver}
            />
          )}
        </Flex>
      </Layout>
    </>
  );
};

export default UsersPage;
