import { useGetUsersByOffset } from "@/apis";
import Layout from "@/components/Layout";
import Pagination from "@/components/Pagination";
import CreateUserModal from "@/containers/users/CreateUserModal";
import UsersTab from "@/containers/users/UsersTab";
import UsersTable from "@/containers/users/UsersTable";
import UsersUtils from "@/containers/users/UsersUtils";
import { Divider, Flex, useDisclosure } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";

const limit = 10;

const UsersOffsetPage = () => {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const router = useRouter();
  const page = router.query?.page ? Number(router.query?.page) : 1;
  const { data } = useGetUsersByOffset({
    offset: (page - 1) * limit,
    limit: 10,
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <CreateUserModal isOpen={isOpen} onClose={onClose} />
        <Flex direction={"column"} gap={4}>
          <UsersUtils onCreateUser={onOpen} />
          <Divider />
          <UsersTab />
          <UsersTable users={data?.data ?? []} />
          <Pagination
            currentPage={page}
            limit={10}
            total={data?.total ?? 0}
            onChange={(page) => router.push({ query: { page } })}
          />
        </Flex>
      </Layout>
    </>
  );
};

export default UsersOffsetPage;
